menu:
- {name: 'team', url: '/people'}
- {name: 'news & updates', url: '/news'}
- {name: 'publications', url: '/publications'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Darya Frank', title: 'Principal Investigator', email: 'darya.frank@manchester.ac.uk', image: 'assets/img/DRF.png'}
- {name: 'Joy Zhang', title: 'Post-doctoral Research Associate', email: 'joy.zhang@manchester.ac.uk',  image: 'assets/img/JZ.jpeg',text: 'Investigating salience-driven memory enhancement via behavioural tagging.'}
- {name: 'Nicholas Adrain', title: 'PhD Student', email: 'nicholas.adrain@manchester.ac.uk',  image: 'assets/img/NA.jpg',text: 'MRC-DTP studentship to study functional correlates of superageing.'}
- {name: 'Marta Garcia Huescar', title: 'PhD Student', email: 'marta.garcia@ctb.upm.es', institution: 'Universidad Politecnica de Madrid', image: 'assets/img/MGH.jpg', text: 'Researches superageing (co-supervised with Bryan Strange).'}
- {name: 'Haoran Guan', title: 'PhD Student', email: 'haoran.guan@manchester.ac.uk', image: 'assets/img/HG.jpeg', text: 'Researches brain lateralisation and its affect on cognition across life span (co-supervised with Daniela Montaldi).'}
- {name: 'Aabhya Parnami', title: 'MRes Student'}
- {name: 'Sophia Georgieva', title: 'Research Assistant'}
- {name: 'Georgia Stokes-Green', title: 'Research Assistant'}
- {name: 'Jingxi Wen', title: 'Research Assistant'}

alumni:
- {name: 'Aysha Janjua', title: 'MRes Student'}
- {name: 'Zhiyun Qin', title: 'MRes Student;  currently Data Scientist'}

social:
- {icon: 'github', link: 'https://github.com/frankmemorylab'}
- {icon: 'bluesky', link: 'https://bsky.app/profile/darya-frank.bsky.social'}

contacts:
- {name: 'Darya Frank', title: 'Royal Society URF', department: 'Andrew Mayes Centre for Cognitive Neuroscience', institution: 'The University of Manchester', email: 'darya.frank@manchester.ac.uk', image: 'assets/img/contact.jpg'}
